services:
  api:
    image: notes-api
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3333:3333"
    restart: always
    volumes:
      - ${PWD}/db:/app/db

    container_name: notes-api
